<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoryConditionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("
            INSERT INTO `category_condition` (`id`, `cat_id`, `condition_name`, `condition_terms`, `condition_price`) VALUES
            (36, 79, 'dfd', '<p><strong>term 4</strong></p>', '0'),
            (39, 80, 'dfd', '<p><strong>sdf asfd dfas</strong></p>', '0'),
            (40, 80, 'dfds', '<ul><li>dfsdf asd</li></ul>', '0'),
            (46, 13, 'NEW', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL&nbsp;OF THESE ARE TRUE:</strong></p><ul><li>Sealed in the original box</li><li>Never been used or activated</li></ul>', '0'),
            (47, 13, 'MINT', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Shows very little or no signs of use&nbsp;</li><li>Fully functional (and comes with straps/bands)</li><li>No Cracks, scratches, or dents</li><li>Has 90% and above battery life</li></ul>', '0'),
            (48, 13, 'GOOD', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Normal signs of use but no cosmetic damage</li><li>Fully functional (and comes with straps/bands)</li><li>No glass cracks or chips&nbsp;</li><li>Has 80% and above battery life</li></ul>', '0'),
            (49, 13, 'FAIR', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Shows heavy signs of use like dents and scratches</li><li>Fully functional (and comes with straps/bands)</li><li>Very little or no glass cracks or chips&nbsp;</li><li>Has 80% and above battery life</li></ul>', '0'),
            (50, 13, 'BROKEN', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ANY OF THESE IS TRUE:</strong></p><ul><li>Cracked glass or damaged LCD damage</li><li>Broken components like buttons, ports, etc</li><li>Deep engraved markings</li><li>Poor battery life</li></ul>', '0'),
            (56, 7, 'NEW', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL&nbsp;OF THESE ARE TRUE:</strong></p><ul><li>Sealed in the original box</li><li>Never been used or activated</li></ul>', '0'),
            (57, 7, 'MINT', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Shows very little or no signs of use&nbsp;</li><li>Fully functional with no missing parts</li><li>No Cracks, scratches, or dents</li><li>Has 90% and above battery life</li></ul>', '0'),
            (58, 7, 'GOOD', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Normal signs of use but no cosmetic damage</li><li>Fully functional with no missing parts</li><li>No glass cracks or chips&nbsp;</li><li>Has 80% and above battery life</li></ul>', '0'),
            (59, 7, 'FAIR', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Shows heavy signs of use like dents and scratches</li><li>Fully functional with no missing parts</li><li>Very little or no glass cracks or chips&nbsp;</li><li>Has 80% and above battery life</li></ul>', '0'),
            (60, 7, 'BROKEN', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ANY OF THESE IS TRUE:</strong></p><ul><li>Cracked glass or damaged LCD damage</li><li>Broken components like buttons, ports, etc</li><li>Deep engraved markings</li><li>Poor battery life</li></ul>', '0'),
            (71, 17, 'NEW', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL&nbsp;OF THESE ARE TRUE:</strong></p><ul><li>Sealed in the original box</li><li>Never been used or activated</li></ul>', '0'),
            (72, 17, 'MINT', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Shows very little or no signs of use&nbsp;</li><li>Fully functional with no missing parts</li><li>No Cracks, scratches, or dents</li><li>Has an excellent battery life</li></ul>', '0'),
            (73, 17, 'GOOD', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Normal signs of use but no cosmetic damage</li><li>Fully functional with no missing parts</li><li>No screen cracks or chips&nbsp;</li><li>Has an excellent battery life</li></ul>', '0'),
            (74, 17, 'FAIR', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Shows heavy signs of use like dents and scratches</li><li>Fully functional with no missing parts</li><li>Very little or no screen cracks or chips&nbsp;</li><li>Has avery good battery life</li></ul>', '0'),
            (75, 17, 'BROKEN', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'✓\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ANY OF THESE IS TRUE:</strong></p><ul><li>Cracked screen or damaged LCD damage</li><li>Broken components like buttons, ports, etc</li><li>Deep engraved markings</li><li>Poor battery life</li></ul>', '0'),
            (76, 6, 'NEW', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'?\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL&nbsp;OF THESE ARE TRUE:</strong></p><ul><li>Sealed in the original box</li><li>Never been used or activated</li></ul>', '0'),
            (77, 6, 'MINT', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'?\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Shows very little or no signs of use&nbsp;</li><li>Fully functional with no missing parts</li><li>No Cracks, scratches, or dents</li><li>Has 90% and above battery life</li></ul>', '0'),
            (78, 6, 'GOOD', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'?\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Normal signs of use but no cosmetic damage</li><li>Fully functional with no missing parts</li><li>No glass cracks or chips&nbsp;</li><li>Has 80% and above battery life</li></ul>', '0'),
            (79, 6, 'FAIR', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'?\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ALL OF THESE ARE TRUE:</strong></p><ul><li>Shows heavy signs of use like dents and scratches</li><li>Fully functional with no missing parts</li><li>Very little or no glass cracks or chips&nbsp;</li><li>Has 80% and above battery life</li></ul>', '0'),
            (80, 6, 'BROKEN', '<p>#id49078 { text-align: left; list-style: none; margin-left: 0; padding-left: 1.6em; text-indent: -1.6em; } #id10202030:before { content: \'?\'; color: rgb(255,177,0); font-size: 20px; } <strong>IF ANY OF THESE IS TRUE:</strong></p><ul><li>Cracked glass or damaged LCD damage</li><li>Broken components like buttons, ports, etc</li><li>Deep engraved markings</li><li>Poor battery life</li></ul>', '0');        
        ");
    }
}
